name: Notificación a Eve cuando se modifica String.xml

on:
  workflow_run:
    workflows: ["Sync-dev-to-Test"]  # Nombre del workflow que debe completarse
    types:
      - completed  # Se ejecutará cuando la acción haya terminado (puede ser: completed, success, failure)

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chequear el repositorio
      uses: actions/checkout@v3

    - name: Verificar información del repositorio
      run: |
        echo "Ramas disponibles:"
        git branch -a
        echo "Historial de commits recientes:"
        git log --oneline -n 10
        echo "Comparación de ramas:"
        git fetch origin Test
        git diff --name-only origin/Test...HEAD || true

    - name: Enviar notificación a Telegram
      uses: appleboy/telegram-action@master
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        to: ${{ secrets.CHAT_ID }}
        message: |
          Amo, se ha modificado el archivo String en DEV ❤ `src/main/resources/twitter/settings/values/strings.xml` en el repositorio `${{ github.repository }}`.
          Commit: `${{ github.event.head_commit.message }}`
          Ver cambios: [Enlace al commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
