name: Notificación a Telegram chan cuando se modifica el archivo YAML

on:
  push:
    branches:
      - Español
    paths:
      - .github/workflows/telegram-notification.yml

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chequear el repositorio
      uses: actions/checkout@v3

    - name: Verificar información del repositorio
      run: |
        echo "Ramas disponibles:"
        git branch -a
        echo "Historial de commits recientes:"
        git log --oneline -n 10
        echo "Comparación de ramas:"
        git fetch origin Español
        git diff --name-only origin/Español...HEAD || true

    - name: Enviar notificación a Telegram
      if: github.event_name == 'push'
      uses: appleboy/telegram-action@master
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        to: ${{ secrets.CHAT_ID }}
        message: |
          Amo, se ha modificado el archivo String en Piko ❤ `.github/workflows/telegram-notification.yml` en el repositorio `${{ github.repository }}`.
          Commit: `${{ github.event.head_commit.message }}`
          Ver cambios: [Enlace al commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
