name: Notificación a Telegram cuando se modifica el archivo YAML

on:
  push:
    branches:
      - Español
    paths:
      - .github/workflows/telegram-notification.yml

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chequear el repositorio
      uses: actions/checkout@v3

    - name: Detectar cambios en el archivo YAML
      id: changes
      run: |
        set -e
        git fetch origin Español
        git diff --name-only origin/Español...HEAD | grep '.github/workflows/telegram-notification.yml' > changes.diff
        if [ -s changes.diff ]; then
          echo "Archivo modificado"
        else
          echo "No hay cambios en el archivo YAML"
          exit 1
        fi

    - name: Mostrar los cambios detectados
      if: failure()
      run: cat changes.diff || true

    - name: Enviar notificación a Telegram
      if: success()
      run: |
        TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID=${{ secrets.CHAT_ID }}
        DIFF=$(cat changes.diff)
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id=${CHAT_ID} \
          -d text="El archivo YAML ha sido modificado:\n\`\`\`\n${DIFF}\n\`\`\`" \
          -d parse_mode=Markdown
