name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - Test
  pull_request:
    branches:
      - Test

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the release step uses its own credentials:
          # https://github.com/cycjimmy/semantic-release-action#private-packages
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: ./gradlew generatePatchesFiles clean

      # - name: Upload patches jar
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: patches
      #     path: build/libs/*.jar

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.Eve }}
        run: npm exec semantic-release

